(() => {
  const root=document.querySelector('.admin-shell'),base=root?.dataset.apiBase||'/api',token=()=>localStorage.getItem('boke_admin_token')||'',state={items:[],sources:[],searchSource:'',searchLabel:'未配置'}
  const $=(selector)=>document.querySelector(selector),html=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))
  async function api(path,options={}){const response=await fetch(base+path,{...options,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token(),...(options.headers||{})}}),json=await response.json().catch(()=>({}));if(!response.ok||json.success===false)throw new Error(json.message||'请求失败');return json.data}
  const notify=(message,failed=false)=>window.notifyAdmin?.(message,failed)
  function message(value,failed=false){const node=$('#manga-message');if(node){node.textContent=value;node.classList.toggle('text-error',failed);node.classList.toggle('text-success',!failed)}}
  function renderSources(){const list=$('#manga-source-list');if(!list)return;list.innerHTML=state.sources.map((source,index)=>`<article class="grid gap-2 rounded-xl bg-base-200/55 p-3 sm:grid-cols-[.75fr_1.4fr_.7fr_auto]"><input class="input input-bordered input-sm rounded-lg" data-manga-source-name="${index}" value="${html(source.name||'')}" placeholder="站点名称"><input class="input input-bordered input-sm rounded-lg" data-manga-source-url="${index}" value="${html(source.url||'')}" placeholder="https://..."><input class="input input-bordered input-sm rounded-lg" data-manga-source-remark="${index}" value="${html(source.remark||'')}" placeholder="备注"><div class="flex items-center gap-2"><label class="flex items-center gap-1 text-xs"><input type="radio" name="manga-default-source" data-manga-source-default="${index}" ${source.is_default?'checked':''}>默认</label><button class="btn btn-ghost btn-xs text-error" type="button" data-manga-source-remove="${index}">×</button></div></article>`).join('')||'<p class="text-sm text-base-content/45">还没有阅读链接。可保存资料后再补充。</p>';list.querySelectorAll('input').forEach((input)=>input.addEventListener('input',syncSources))}
  function syncSources(){state.sources=state.sources.map((source,index)=>({...source,name:$(`[data-manga-source-name="${index}"]`)?.value||'',url:$(`[data-manga-source-url="${index}"]`)?.value||'',remark:$(`[data-manga-source-remark="${index}"]`)?.value||'',is_default:Boolean($(`[data-manga-source-default="${index}"]`)?.checked),sort_order:index}))}
  function reset(){const form=$('#manga-form');form?.reset();if(form){form.elements.namedItem('id').value='';form.elements.namedItem('source').value='';form.elements.namedItem('library_type').value='network';form.elements.namedItem('is_active').checked=true}state.sources=[];renderSources();message('')}
  function fill(item){reset();const form=$('#manga-form');['id','title','slug','original_title','author','cover','publication','external_id','source_url','source','library_type','status','progress','rating','description','sort_order'].forEach((name)=>{const field=form.elements.namedItem(name);if(field)field.value=item[name]??''});form.elements.namedItem('is_active').checked=Boolean(item.is_active);state.sources=(item.read_sources||[]).map((source)=>({...source,is_default:Boolean(source.is_default)}));renderSources();form.scrollIntoView({behavior:'smooth',block:'start'})}
  async function load(){if(!token())return;state.items=await api('/admin/manga')||[];const target=$('#manga-local-target');if(target){const selected=target.value;target.innerHTML='<option value="">新建本地漫画</option>'+state.items.filter((item)=>item.library_type==='local').map((item)=>'<option value="'+item.id+'">'+html(item.title)+'</option>').join('');target.value=selected}const list=$('#manga-list');if(!list)return;list.innerHTML=state.items.map((item)=>`<article class="admin-personal-item"><header><span>${html({reading:'在读',finished:'读完',planned:'想读',paused:'暂放'}[item.status]||'在读')}</span><small>${item.library_type==='local'?(item.volume_count||0)+' 卷 · '+(item.chapter_count||0)+' 章':(item.read_sources||[]).length+' 个阅读源'}</small></header><strong>${html(item.title)}</strong><p>${html(item.author||item.original_title||'作者未填写')}</p><footer><button data-manga-edit="${item.id}">编辑</button><a href="/manga/${encodeURIComponent(item.slug)}" target="_blank">查看</a><button class="is-danger" data-manga-delete="${item.id}">删除</button></footer></article>`).join('')||'<p class="text-sm text-base-content/45">还没有漫画，先从左侧检索。</p>'}
  function applySearchConfig(config){if(!config)return;state.searchSource=config.defaults?.manga||'';state.searchLabel=config.sources?.find((item)=>item.id===state.searchSource)?.label||state.searchSource||'未配置';const status=$('#manga-search-status');if(status)status.textContent=`当前使用设置中的默认源：${state.searchLabel}`}
  async function loadSourceSetting(){try{applySearchConfig(await api('/admin/search-sources'))}catch(error){const status=$('#manga-search-status');if(status)status.textContent=error.message}}
  async function search(){const query=$('#manga-search-query').value.trim(),status=$('#manga-search-status'),results=$('#manga-search-results');if(!query){status.textContent='请输入漫画名称或数据源 ID';return}status.textContent=`正在通过 ${state.searchLabel} 检索…`;results.innerHTML='';try{const params=new URLSearchParams();if(/^\d+$/.test(query))params.set('id',query);else params.set('q',query);const items=await api('/admin/manga/search?'+params);results.innerHTML=items.map((item,index)=>`<button class="grid grid-cols-[3rem_1fr] gap-3 rounded-xl bg-base-100/70 p-2 text-left" type="button" data-manga-import="${index}">${item.cover?`<img class="h-16 w-12 rounded-lg object-cover" src="${html(item.cover)}" alt="">`:'<span class="grid h-16 w-12 place-items-center rounded-lg bg-base-200">漫</span>'}<span class="min-w-0"><b class="block truncate">${html(item.title)}</b><small class="block truncate text-base-content/45">${html(item.original_title||item.publication||'')}</small><em class="mt-1 block truncate text-xs not-italic text-base-content/55">${html(item.description||'暂无简介')}</em></span></button>`).join('');results._items=items;status.textContent=`找到 ${items.length} 个结果 · ${state.searchLabel}`}catch(error){status.textContent=error.message;notify(error.message,true)}}
  window.addEventListener('content-search-sources-updated',(event)=>applySearchConfig(event.detail));
  $('#manga-form')?.addEventListener('submit',async(event)=>{event.preventDefault();syncSources();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),id=data.id;delete data.id;data.is_active=form.elements.namedItem('is_active').checked;data.read_sources=state.sources.filter((source)=>source.url.trim());try{const item=await api(id?'/admin/manga/'+id:'/admin/manga',{method:id?'PUT':'POST',body:JSON.stringify(data)});await load();fill(item);message('漫画已保存')}catch(error){message(error.message,true)}})
  document.addEventListener('click',async(event)=>{const target=event.target.closest('button');if(!target)return;try{if(target.dataset.panelTab==='manga'){await Promise.all([load(),loadSourceSetting()])}if(target.dataset.mangaEdit)fill(state.items.find((item)=>String(item.id)===target.dataset.mangaEdit));if(target.dataset.mangaDelete&&confirm('确定删除这部漫画吗？')){await api('/admin/manga/'+target.dataset.mangaDelete,{method:'DELETE'});await load()}if(target.dataset.mangaSourceRemove!==undefined){syncSources();state.sources.splice(Number(target.dataset.mangaSourceRemove),1);if(state.sources.length&&!state.sources.some((source)=>source.is_default))state.sources[0].is_default=true;renderSources()}if(target.dataset.mangaImport!==undefined){const item=$('#manga-search-results')._items?.[Number(target.dataset.mangaImport)];if(item){fill({...item,status:'reading',is_active:true,read_sources:item.source_url?[{name:item.source_label||'资料页',url:item.source_url,remark:'可替换成实际阅读链接',is_default:true}]:[]});message('元数据已填入，请确认阅读源后保存')}}}catch(error){notify(error.message,true)}})
  $('#manga-local-import')?.addEventListener('click',async()=>{const file=$('#manga-local-file')?.files?.[0],button=$('#manga-local-import'),progress=$('#manga-import-progress');if(!file)return notify('请选择 CBZ 或 ZIP 漫画包',true);const body=new FormData();body.append('file',file);body.append('title',$('#manga-local-title')?.value.trim()||'');body.append('author',$('#manga-local-author')?.value.trim()||'');body.append('manga_id',$('#manga-local-target')?.value||'');body.append('volume_title',$('#manga-local-volume')?.value.trim()||'');button.disabled=true;button.textContent='正在导入…';progress.hidden=false;progress.removeAttribute('value');try{const response=await fetch(base+'/admin/manga/import',{method:'POST',headers:{Authorization:'Bearer '+token()},body}),json=await response.json().catch(()=>({}));if(!response.ok||json.success===false)throw new Error(json.message||'导入失败');progress.value=100;await load();fill(json.data);message(json.message||'本地漫画已导入');notify('本地漫画已导入')}catch(error){message(error.message,true);notify(error.message,true)}finally{button.disabled=false;button.textContent='导入本地漫画';setTimeout(()=>{progress.hidden=true;progress.value=0},800)}});
  $('#manga-source-add')?.addEventListener('click',()=>{syncSources();state.sources.push({name:'阅读站点',url:'',remark:'',is_default:state.sources.length===0,sort_order:state.sources.length});renderSources()});$('#manga-reset')?.addEventListener('click',reset);$('#manga-search')?.addEventListener('click',search);$('#manga-search-query')?.addEventListener('keydown',(event)=>{if(event.key==='Enter'){event.preventDefault();search()}});reset()
})()
