import { Response } from 'express'
import db from '../config/database'
import { AuthRequest } from '../middleware/auth'
import { DeviceRequest } from '../middleware/device'
import { error, success } from '../utils/response'

const clean=(value:unknown,max=500)=>String(value??'').trim().slice(0,max)
const integer=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Math.trunc(Number(value)):fallback
const json=(value:unknown)=>{try{return JSON.parse(String(value||'{}'))}catch{return {}}}

export function importJobs(_req:AuthRequest,res:Response){const rows=db.prepare('SELECT * FROM content_import_jobs ORDER BY id DESC LIMIT 100').all() as any[];rows.forEach(row=>row.options=json(row.options));return success(res,rows)}
export function createImportJob(req:AuthRequest,res:Response){const filename=clean(req.body?.filename,255);if(!filename)return error(res,'缺少文件名','VALIDATION_ERROR');const kind=['book','manga','media'].includes(req.body?.kind)?req.body.kind:'unknown';const result=db.prepare('INSERT INTO content_import_jobs (user_id,kind,filename,status,progress,options) VALUES (?,?,?,?,?,?)').run(req.userId||null,kind,filename,'pending',0,JSON.stringify(req.body?.options||{}));return success(res,db.prepare('SELECT * FROM content_import_jobs WHERE id=?').get(result.lastInsertRowid))}
export function updateImportJob(req:AuthRequest,res:Response){const id=integer(req.params.id),current=db.prepare('SELECT * FROM content_import_jobs WHERE id=?').get(id) as any;if(!current)return error(res,'导入任务不存在','NOT_FOUND',404);const status=['pending','processing','completed','failed','cancelled'].includes(req.body?.status)?req.body.status:current.status;db.prepare("UPDATE content_import_jobs SET status=?,progress=?,result_type=?,result_id=?,error=?,options=?,updated_at=datetime('now') WHERE id=?").run(status,Math.max(0,Math.min(100,integer(req.body?.progress,current.progress))),clean(req.body?.result_type??current.result_type,30),integer(req.body?.result_id,current.result_id)||null,clean(req.body?.error??current.error,2000),JSON.stringify(req.body?.options??json(current.options)),id);return success(res,db.prepare('SELECT * FROM content_import_jobs WHERE id=?').get(id))}
export function subscriptions(req:AuthRequest,res:Response){return success(res,db.prepare('SELECT * FROM content_subscriptions WHERE user_id=? ORDER BY is_active DESC,unread_count DESC,updated_at DESC').all(req.userId))}
export function createSubscription(req:AuthRequest,res:Response){const title=clean(req.body?.title,160),url=clean(req.body?.url,1000);if(!title||!/^https?:\/\//i.test(url))return error(res,'请输入名称和有效网址','VALIDATION_ERROR');try{const result=db.prepare('INSERT INTO content_subscriptions (user_id,kind,title,url,icon,check_interval) VALUES (?,?,?,?,?,?)').run(req.userId,clean(req.body?.kind,30)||'web',title,url,clean(req.body?.icon,1000),Math.max(15,integer(req.body?.check_interval,360)));return success(res,db.prepare('SELECT * FROM content_subscriptions WHERE id=?').get(result.lastInsertRowid))}catch{return error(res,'该订阅已经存在','DUPLICATE',409)}}
export function updateSubscription(req:AuthRequest,res:Response){const id=integer(req.params.id),row=db.prepare('SELECT * FROM content_subscriptions WHERE id=? AND user_id=?').get(id,req.userId) as any;if(!row)return error(res,'订阅不存在','NOT_FOUND',404);db.prepare("UPDATE content_subscriptions SET title=?,url=?,kind=?,icon=?,check_interval=?,unread_count=?,is_active=?,updated_at=datetime('now') WHERE id=?").run(clean(req.body?.title??row.title,160),clean(req.body?.url??row.url,1000),clean(req.body?.kind??row.kind,30),clean(req.body?.icon??row.icon,1000),Math.max(15,integer(req.body?.check_interval,row.check_interval)),Math.max(0,integer(req.body?.unread_count,row.unread_count)),req.body?.is_active===undefined?row.is_active:(req.body.is_active?1:0),id);return success(res,db.prepare('SELECT * FROM content_subscriptions WHERE id=?').get(id))}
export function removeSubscription(req:AuthRequest,res:Response){const result=db.prepare('DELETE FROM content_subscriptions WHERE id=? AND user_id=?').run(integer(req.params.id),req.userId);return result.changes?success(res,null,'订阅已删除'):error(res,'订阅不存在','NOT_FOUND',404)}
export function relations(req:AuthRequest,res:Response){const type=clean(req.query.type,30),id=integer(req.query.id);const rows=type&&id?db.prepare('SELECT * FROM content_relations WHERE (source_type=? AND source_id=?) OR (target_type=? AND target_id=?) ORDER BY sort_order,id').all(type,id,type,id):db.prepare('SELECT * FROM content_relations ORDER BY id DESC LIMIT 200').all();return success(res,rows)}
export function createRelation(req:AuthRequest,res:Response){const sourceType=clean(req.body?.source_type,30),targetType=clean(req.body?.target_type,30),sourceId=integer(req.body?.source_id),targetId=integer(req.body?.target_id);if(!sourceType||!targetType||!sourceId||!targetId||(sourceType===targetType&&sourceId===targetId))return error(res,'请选择两个不同的内容','VALIDATION_ERROR');try{const result=db.prepare('INSERT INTO content_relations (source_type,source_id,target_type,target_id,relation_type,note,sort_order) VALUES (?,?,?,?,?,?,?)').run(sourceType,sourceId,targetType,targetId,clean(req.body?.relation_type,30)||'related',clean(req.body?.note,500),integer(req.body?.sort_order));return success(res,db.prepare('SELECT * FROM content_relations WHERE id=?').get(result.lastInsertRowid))}catch{return error(res,'这条关系已经存在','DUPLICATE',409)}}
export function removeRelation(req:AuthRequest,res:Response){const result=db.prepare('DELETE FROM content_relations WHERE id=?').run(integer(req.params.id));return result.changes?success(res,null,'内容关系已删除'):error(res,'内容关系不存在','NOT_FOUND',404)}
export function readingCenter(req:DeviceRequest,res:Response){const books=db.prepare("SELECT 'book' kind,b.id,b.slug,b.title,b.cover,s.position progress,s.updated_at,v.title section_title,c.title chapter_title,('/books/'||b.slug||'/'||v.slug||'/'||c.slug) href FROM reading_states s JOIN books b ON b.id=s.book_id LEFT JOIN book_volumes v ON v.id=s.volume_id LEFT JOIN book_chapters c ON c.id=s.chapter_id WHERE s.user_id=? AND b.deleted_at IS NULL").all(req.deviceUserId!) as any[];const manga=db.prepare("SELECT 'manga' kind,m.id,m.slug,m.title,m.cover,CASE WHEN (SELECT COUNT(*) FROM manga_pages WHERE chapter_id=c.id)>1 THEN CAST(s.page_index AS REAL)/((SELECT COUNT(*) FROM manga_pages WHERE chapter_id=c.id)-1) ELSE 0 END progress,s.updated_at,v.title section_title,c.title chapter_title,('/manga/'||m.slug||'/'||v.slug||'/'||c.slug) href FROM manga_reading_states s JOIN manga_items m ON m.id=s.manga_id LEFT JOIN manga_volumes v ON v.id=s.volume_id LEFT JOIN manga_chapters c ON c.id=s.chapter_id WHERE s.user_id=? AND m.is_active=1").all(req.deviceUserId!) as any[];return success(res,[...books,...manga].sort((a,b)=>String(b.updated_at).localeCompare(String(a.updated_at))))}